### PR TITLE
!!! Major Rework

### PR DESCRIPTION
**Pull request by bwaidelich**
This is a preparation for version 2.0 of this package.
It changes most of the APIs and comes with some new features:

* Dependencies:
  *  `neos/flow` 5.2 compatibility
  *  updated `pragmarx/google2fa` and `bacon/bacon-qr-code` packages
* Persistence:
  *  2FA state is no longer stored in the `neos_flow_security_account` table
     but in a separate table `yeebase_twofactorauthentication_secret` for
     greater compatibility/extensibility
* Security:
  * OTPs can only be used once now!
  * QR Code is created locally in order to avoid the secret to be sent over
    the wire (note: The QR Code is a SVG by default that can be used inline)

### CODE REVIEW

**Comment by johannessteu** [comment]
Could we also add https://github.com/t3n/coding-standard as  a dev-dep?

**Comment by bwaidelich** [comment]
> Could we also add https://github.com/t3n/coding-standard as a dev-dep?

Ich mach das mal, auch wenn ich mangels Beschreibung keine Ahnung habe was genau das Package macht :)

**Comment by bwaidelich** [comment]
@johannessteu Done :)

**Comment by johannessteu** [comment]
Coding-Standard:

Könnten wir dann per travis checken lassen wie hier:
https://github.com/t3n/graphql/blob/master/.travis.yml

und vorher noch eine phpcs dist reinwerfen:
https://github.com/t3n/graphql/blob/master/phpcs.xml.dist

**Comment by bwaidelich** [comment]
Ah, sehr cool!

**Review by johannessteu — APPROVED** [review]

**Pull request merged**
